### ISSUE TITLE
Remaining dust with `positionManager.moveLiquidity` usage

### ISSUE THREAD

**Issue by halaprix** [ajna-finance/ajna-core#690]
When a user moves liquidity between a bucket with a staked or unstated NFT there is an accounting error causing some of the lps to stay in the `from` bucket and account for PositionManager.

![image](https://user-images.githubusercontent.com/6533433/225566572-2a4c5b8b-1904-4c88-ad80-2379c0112631.png)

Steps to replicate:
- create several lender positions with NFTs
- increase time
- use `PositionManager.moveLiqudity()`

**Comment by EdNoepel** [comment]
This bug is caused because `PositionManager.moveLiquidity` is not accruing interest prior to calling `_lpsToQuoteToken`.  As such, we ignore interest the lender earned since the last time pool interest had accrued, leaving significant dust in the bucket.

To remedy, `PositionManager.moveLiquidity` should call `Pool.updateInterest()` prior to `bucketInfo` and `_lpsToQuoteToken` calls.

**Comment by EdNoepel** [comment]
Fixed by #700.
